CREATE TYPE star_rating AS ENUM ('1', '2', '3', '4', '5');

-- Create the table anew
create table bookmarks (
  id INTEGER primary key generated by default as identity,
  title text not null,
  url text not null,
  description text,
  rating star_rating ENUM not null,
);

-- INSERT INTO bookmarks (title, url, rating, description)
-- VALUES
--   ('Thinkful', 'https://www.thinkful.com', '5', 'Think outside the classroom'),
--   ('Google', 'https://www.google.com', '4', 'Where we find everything else'),
--   ('MDN', 'https://developer.mozilla.org', '5', 'The only place to find web documentation');
