-- First, remove the table if it exists
drop table if exists bookmarks;

-- Create the table anew
create table bookmarks (
  id INTEGER primary key generated by default as identity,
  title text,
  description text
);

-- insert some test data
-- Using a multi-row insert statement here
insert into customers (title, description)
values
  ('filler', 'how to fill in space'),